version: '3.9'
services:
  postgres:
    container_name: postgress-kartowka
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: admin # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: postgres_db # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kartowka-network
  postgres-admin:
    container_name: postgres-admin-kartowka
    image: dpage/pgadmin4:latest
    ports:
      - '5433:5433'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5433
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - kartowka-network
volumes:
  postgres-data:
  pgadmin-data:

networks:
  kartowka-network:
    external: true

